### ISSUE TITLE
Add Out-of-Band Protection for MAX runtime

### ISSUE THREAD

**Issue by Sy14r** [Sy14r/Cryptbreaker#30]
Can't recreate the hanging bug but lets add an additional protection to ensure no run-away resource issues. A configurable serverless function run on a schedule to find and kill tagged resources that have a run time of > X hours (or minutes or whatever....)

### ToDo
- [ ] Ensure EC2 instances are tagged with the 'Cryptbreaker' tag *and* a 'CBID' tag that is the installation id for the particular CB install
- [ ] Create a default scheduled serverless function to every 5 min check for resources that have been up more than 2 hours and kill them
- [ ] Delete S3 resources tagged for that job as well
- [ ] Expose configuration options for the serverless protection task in the CB admin panel
  - [ ] Enable/Disable
  - [ ] Configurable threshold time
  - [ ] Configurable schedule rate (X minutes, X hours)

### Note
We will want the Job UI to gracefully handle when resources just disappear (either admin killed via AWS or the serverless job killed it)

**Comment by Sy14r** [comment]
As an additional note, in addition to the serverless function (and this may be a per instance serverless function vs a recurring one) there may be optimizations that can be made via modifiying the userdata script as well. Maybe something like:

`sleep X; ./kill-instance.sh &`

Where `kill-instance.sh` is a uploaded script that just finds and terminates the instance (not graceful but this is intended as a failsafe and a loss of data wouldn't be catastrophic as the job could be re-run)

**Comment by Sy14r** [comment]
Using a serverless function is more stuff to clean up... if we can update just the user script it think it would be good.... though with other bugs fixed this *may* be superfluous now.... will wait and see in future tests if we hit edge cases where we need this additional control.... not implementing for now..
